title: Benvinguts al Blog de Francesc!
author: Francesc Navarro
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  En aquest bloc trobareu diferents aplicacions web fetes en HTML, 
  CSS, JavaScript, PHP, Java, SQL i diferents frameworks com React, 
  NodeJS, Spring i Laravel.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
